-- MySQL Script generated by MySQL Workbench
-- Mon Oct 16 20:25:57 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Especialidade` (
  `cd_especialidade` INT NOT NULL,
  `ds_especialidade` VARCHAR(255) NULL,
  `cd_cbo` INT NULL,
  PRIMARY KEY (`cd_especialidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agenda` (
  `cd_agenda` INT NOT NULL,
  `ds_agenda` VARCHAR(255) NULL,
  `cd_medico` INT NOT NULL,
  `cd_especialidade` INT NOT NULL,
  `ie_tipo_agenda` VARCHAR(4) NULL,
  PRIMARY KEY (`cd_agenda`),
  INDEX `fk_Agenda_Especialidade1_idx` (`cd_especialidade` ASC),
  CONSTRAINT `fk_Agenda_Especialidade1`
    FOREIGN KEY (`cd_especialidade`)
    REFERENCES `mydb`.`Especialidade` (`cd_especialidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Convenio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Convenio` (
  `cd_convenio` INT NOT NULL AUTO_INCREMENT,
  `ds_convenio` VARCHAR(255) NULL,
  `cd_cgc` VARCHAR(14) NULL,
  `nr_rg_ans` INT NULL,
  `ie_tipo_convenio` VARCHAR(4) NULL,
  PRIMARY KEY (`cd_convenio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa_Fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa_Fisica` (
  `cd_pessoa_fisica` INT NOT NULL AUTO_INCREMENT,
  `nr_prontuario` INT NOT NULL,
  `nm_pessoa` VARCHAR(255) NOT NULL,
  `nm_social` VARCHAR(255) NULL,
  `cd_cpf` VARCHAR(11) NULL,
  `nr_rg` VARCHAR(45) NULL,
  `nr_passaporte` VARCHAR(45) NULL,
  `cd_mae` INT NULL,
  `ds_mae` VARCHAR(255) NULL,
  `cd_religiao` INT NULL,
  `cd_pai` INT NULL,
  `ds_pai` VARCHAR(255) NULL,
  `dt_nascimento` DATE NULL,
  `ie_sexo` VARCHAR(4) NULL,
  `cd_nacionalidade` INT NOT NULL,
  `dt_atualizacao` DATE NOT NULL,
  `dt_criacao` DATE NOT NULL,
  PRIMARY KEY (`cd_pessoa_fisica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Atendimento` (
  `nr_atendimento` INT NOT NULL AUTO_INCREMENT,
  `cd_pessoa_fisica` INT NOT NULL,
  `dt_atendimento` DATE NULL,
  `cd_convenio` INT NULL,
  `cd_medico` INT NULL,
  `cd_responsavel` INT NULL,
  `ie_tipo_atendimento` VARCHAR(4) NULL,
  PRIMARY KEY (`nr_atendimento`),
  INDEX `fk_Atendimento_Pessoa_Fisica1_idx` (`cd_pessoa_fisica` ASC),
  CONSTRAINT `fk_Atendimento_Pessoa_Fisica1`
    FOREIGN KEY (`cd_pessoa_fisica`)
    REFERENCES `mydb`.`Pessoa_Fisica` (`cd_pessoa_fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Agendamento` (
  `nr_sequencia` INT NOT NULL AUTO_INCREMENT,
  `cd_pessoa_fisica` INT NOT NULL,
  `nr_atendimento` INT NOT NULL,
  `dt_consulta` DATE NULL,
  `dt_agendamento` DATE NULL,
  `cd_convenio` INT NOT NULL,
  `cd_agenda` INT NOT NULL,
  `ie_status` VARCHAR(2) NULL,
  `classif_agendamento` VARCHAR(45) NULL,
  INDEX `fk_Agendamento_Convenio1_idx` (`cd_convenio` ASC),
  PRIMARY KEY (`nr_sequencia`),
  INDEX `fk_Agendamento_Agenda1_idx` (`cd_agenda` ASC),
  INDEX `fk_Agendamento_Pessoa_Fisica1_idx` (`cd_pessoa_fisica` ASC),
  INDEX `fk_Agendamento_Atendimento1_idx` (`nr_atendimento` ASC),
  CONSTRAINT `fk_Agendamento_Convenio1`
    FOREIGN KEY (`cd_convenio`)
    REFERENCES `mydb`.`Convenio` (`cd_convenio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agendamento_Agenda1`
    FOREIGN KEY (`cd_agenda`)
    REFERENCES `mydb`.`Agenda` (`cd_agenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agendamento_Pessoa_Fisica1`
    FOREIGN KEY (`cd_pessoa_fisica`)
    REFERENCES `mydb`.`Pessoa_Fisica` (`cd_pessoa_fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agendamento_Atendimento1`
    FOREIGN KEY (`nr_atendimento`)
    REFERENCES `mydb`.`Atendimento` (`nr_atendimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evolucao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evolucao` (
  `cd_evolucao` INT NOT NULL AUTO_INCREMENT,
  `ds_evolucao` VARCHAR(4000) NULL,
  `nr_atendimento` INT NOT NULL,
  `dt_evolucao` DATE NULL,
  `dt_liberacao` DATE NULL,
  `dt_inativacao` DATE NULL,
  PRIMARY KEY (`cd_evolucao`),
  INDEX `fk_Evolucao_Atendimento1_idx` (`nr_atendimento` ASC),
  CONSTRAINT `fk_Evolucao_Atendimento1`
    FOREIGN KEY (`nr_atendimento`)
    REFERENCES `mydb`.`Atendimento` (`nr_atendimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turno_Agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turno_Agenda` (
  `nr_sequencia` INT NOT NULL AUTO_INCREMENT,
  `cd_agenda` INT NOT NULL,
  `ie_dia` VARCHAR(4) NULL,
  `hr_inicio` DATE NULL,
  `hr_fim` DATE NULL,
  `intervalo_minutos` INT NULL,
  `qt_antecendencia_min` INT NULL,
  PRIMARY KEY (`nr_sequencia`),
  CONSTRAINT `fk_Turno_Agenda_Agenda1`
    FOREIGN KEY (`cd_agenda`)
    REFERENCES `mydb`.`Agenda` (`cd_agenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Procedimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Procedimento` (
  `cd_procedimento` INT NOT NULL AUTO_INCREMENT,
  `ds_procedimento` VARCHAR(255) NULL,
  `cd_area` INT NULL,
  `cd_grupo` INT NULL,
  `cd_especialidade` INT NULL,
  PRIMARY KEY (`cd_procedimento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proc_Agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proc_Agendamento` (
  `nr_sequencia` INT NOT NULL AUTO_INCREMENT,
  `nr_seq_agendamento` INT NOT NULL,
  `cd_procedimento` INT NOT NULL,
  `quantidade` INT NULL,
  `ie_lado` VARCHAR(4) NULL,
  `observacao` VARCHAR(500) NULL,
  INDEX `fk_Proc_Agendamento_Procedimento1_idx` (`cd_procedimento` ASC),
  PRIMARY KEY (`nr_sequencia`),
  CONSTRAINT `fk_Proc_Agendamento_Agendamento1`
    FOREIGN KEY (`nr_seq_agendamento`)
    REFERENCES `mydb`.`Agendamento` (`nr_sequencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proc_Agendamento_Procedimento1`
    FOREIGN KEY (`cd_procedimento`)
    REFERENCES `mydb`.`Procedimento` (`cd_procedimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contato` (
  `nr_sequencia` INT NOT NULL AUTO_INCREMENT,
  `cd_pessoa_fisica` INT NOT NULL,
  `cd_cep` VARCHAR(8) NULL,
  `numero` INT NULL,
  `ds_logradouro` VARCHAR(255) NULL,
  `complemento` VARCHAR(255) NULL,
  `e-mail` VARCHAR(255) NULL,
  PRIMARY KEY (`nr_sequencia`),
  CONSTRAINT `fk_Contato_Pessoa_Fisica1`
    FOREIGN KEY (`cd_pessoa_fisica`)
    REFERENCES `mydb`.`Pessoa_Fisica` (`cd_pessoa_fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tel_Contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tel_Contato` (
  `nr_sequencia` INT NOT NULL AUTO_INCREMENT,
  `nr_seq_contato` INT NOT NULL,
  `nr_fax` VARCHAR(45) NULL,
  `nr_fixo` VARCHAR(45) NULL,
  `nr_cel` VARCHAR(45) NULL,
  PRIMARY KEY (`nr_sequencia`),
  CONSTRAINT `fk_Tel_Contato_Contato1`
    FOREIGN KEY (`nr_seq_contato`)
    REFERENCES `mydb`.`Contato` (`nr_sequencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `nr_sequencia` INT NOT NULL AUTO_INCREMENT,
  `cd_pessoa_fisica` INT NOT NULL,
  `nm_usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`nr_sequencia`),
  CONSTRAINT `fk_Usuario_Pessoa_Fisica1`
    FOREIGN KEY (`cd_pessoa_fisica`)
    REFERENCES `mydb`.`Pessoa_Fisica` (`cd_pessoa_fisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
